# Generated by Django 5.1.3 on 2024-11-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('scheduled', 'Запланировано'), ('in_progress', 'В процессе'), ('completed', 'Завершено')], default='pending', max_length=20),
        ),
    ]
