# Generated by Django 5.1.3 on 2024-11-22 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
