# Generated by Django 5.1.3 on 2024-11-27 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
