# Generated by Django 5.2 on 2025-05-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_delete_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
