# Generated by Django 5.2 on 2025-05-06 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_customuser_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
