# Generated by Django 5.1.1 on 2024-10-12 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prepods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=35)),
                ('description', models.CharField(max_length=250)),
                ('age', models.PositiveIntegerField()),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Каталог',
                'verbose_name_plural': 'Каталоги',
            },
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
    ]
