# Generated by Django 5.1.1 on 2024-10-12 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog2', '0002_prepods_delete_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepods',
            name='age',
            field=models.PositiveIntegerField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='prepods',
            name='description',
            field=models.CharField(max_length=250, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='prepods',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='prepods',
            name='subject',
            field=models.CharField(max_length=35, verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='prepods',
            name='title',
            field=models.CharField(max_length=50, verbose_name='ФИО'),
        ),
    ]
