# Generated by Django 5.1.1 on 2024-10-12 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog2', '0003_alter_prepods_age_alter_prepods_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepods',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
