# Generated by Django 5.1.1 on 2024-10-12 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog2', '0004_prepods_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepods',
            name='contact_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка для связи'),
        ),
        migrations.AlterField(
            model_name='prepods',
            name='age',
            field=models.CharField(max_length=8, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='prepods',
            name='avatar',
            field=models.ImageField(upload_to='img/', verbose_name='Аватар'),
        ),
    ]
