# Generated by Django 5.1.3 on 2024-11-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prepods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='ФИО')),
                ('subject', models.CharField(max_length=35, verbose_name='Предмет')),
                ('description', models.CharField(max_length=250, verbose_name='Описание')),
                ('age', models.CharField(max_length=8, verbose_name='Возраст')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Рейтинг')),
                ('avatar', models.ImageField(upload_to='img/', verbose_name='Аватар')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('contact_link', models.URLField(blank=True, null=True, verbose_name='Ссылка для связи')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Одобрено')),
            ],
            options={
                'verbose_name': 'объявление',
                'verbose_name_plural': 'Каталоги',
            },
        ),
    ]
