# Generated by Django 5.1.3 on 2024-11-15 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название предмета')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Prepods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=False, verbose_name='Одобрено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepods', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog2.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'объявление',
                'verbose_name_plural': 'Каталоги',
            },
        ),
    ]
