# Generated by Django 5.1.2 on 2024-11-11 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog2', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название предмета')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.RemoveField(
            model_name='prepods',
            name='age',
        ),
        migrations.RemoveField(
            model_name='prepods',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='prepods',
            name='contact_link',
        ),
        migrations.RemoveField(
            model_name='prepods',
            name='date',
        ),
        migrations.RemoveField(
            model_name='prepods',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='prepods',
            name='title',
        ),
        migrations.AlterField(
            model_name='prepods',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog2.subject', verbose_name='Предмет'),
        ),
    ]
