# Generated by Django 5.1.3 on 2025-05-07 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog2', '0003_rename_prepods_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='price',
            field=models.PositiveIntegerField(default=300, verbose_name='Цена за занятие (руб)'),
        ),
    ]
