# Generated by Django 5.1.3 on 2025-05-07 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog2', '0004_announcement_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='price',
        ),
    ]
