# Generated by Django 5.1.1 on 2024-10-18 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog2', '0005_prepods_contact_link_alter_prepods_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepods',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Одобрено'),
        ),
    ]
