# Generated by Django 5.1.1 on 2024-10-25 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog2', '0007_alter_prepods_options_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
